import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

# List of athlete names
athlete_names = [
    "Aksel Rosenvinge",
    "Akseli Pitkänen",
    "Aleksandr Terentev",
    "Aleksandra Trofimova",
    "Alena Baranova",
    "Alessandro Zenoni",
    "Alevtina Tanygina",
    "Alex Vanzetta",
    "Alexander Klugen",
    "Alexei Louchtine",
    "Alexey Chervotkin",
    "Anamarija Lampic",
    "Anastasia Sedova",
    "Anastassia Kazakoul",
    "Andreas Bergsland",
    "Andrei Kuznetsov",
    "Andrei Nekrasov",
    "Andrey Feller",
    "Ania Weber",
    "Anja Mandeljc",
    "Anja Weber",
    "Anna Milerska",
    "Anne Kyllonen",
    "Anne-Tine Bendixen Markset",
    "Antonia Fraebel",
    "Antti Ojansivu",
    "Artem Maltsev",
    "Artem Maximov",
    "Barbara Blasková",
    "Betty Ann Bjerkreim Nilsen",
    "Carin Holmberg",
    "Christoffer Lindvall",
    "Claudia Straube",
    "Cla-Ursin Nufer",
    "Daniel Herzog",
    "Darya Godovanichenko",
    "Davide Ghio",
    "Denise Herrmann",
    "Diana Sapronova",
    "Didrik Tonseth",
    "Ebba Andresen",
    "Edvard Sandvik",
    "Egor Kazarinov",
    "Egor Lonchakov",
    "Eirik Sverdrup Augdal",
    "Ekaterina Meged",
    "Elena Kucheva",
    "Elias Danielsson",
    "Elin Neaslund",
    "Elina Pienimäki",
    "Eliska Hajkova",
    "Elsa Torvinen",
    "Emilia Soudunsaari",
    "Emilien Louvrier",
    "Estelle Darbellay",
    "Eva Wolf",
    "Even Skjelbostad",
    "Evgeniy Vakhrushev",
    "Evgeniya Bazarnova",
    "Evgeniya Oshchepkova",
    "Evguenia Kravtsová",
    "Fabio Santus",
    "Fanny Kukonlehto",
    "Federico Pozzi",
    "Fedor Stroitelev",
    "Filippo Cagnati",
    "Florian Perez",
    "František Janečko",
    "Frederico Clementi",
    "Gabriele Matli",
    "Gaspard Rousset",
    "Gleb Retivikh",
    "Hanka Randáková",
    "Hanna Kolb",
    "Hannes Oberhofer",
    "Hans Gronnvoll",
    "Hans Christer Holund",
    "Hans Gronnvoll",
    "Haavard Solaas Taugbol",
    "Heidi Bucher",
    "Helen Hoffmann",
    "Herman Martens Meyer",
    "Hilde Losgard Landheim",
    "Hugo Nilsson",
    "Ike Melnits",
    "Illia Tretiakov",
    "Inna Srmirnova",
    "Irina Ivanova",
    "Irina Nazarova",
    "Irina Terenijeva",
    "Iris De Martin Pinter",
    "Iryna Nafranovich",
    "Ivan Kovalev",
    "Jacob Vogt",
    "Jakub Graef",
    "Jan Rykr",
    "Jana Svobodova",
    "Janosch Brugger",
    "Jasmin Kahara",
    "Jegor Kasarinow",
    "Jenny Wissting",
    "Jens Junes",
    "Jesse Kähärä",
    "Jiri Tuz",
    "Johan Olsson",
    "Johanna Heinanen",
    "Jonáš Jan Hellmich",
    "Jonatan Lindberg",
    "Josefiina Book",
    "Julia Tihonova",
    "Julien Arnaud",
    "Juri Ostrovski",
    "Katarína Garajová",
    "Katerina Hanusova",
    "Katherine Sauerbrey",
    "Konstantin Gostiaev",
    "Kristian Horntvedt",
    "Kristin Gausen",
    "Kristina Kuskova",
    "Kristina Smigun",
    "Lari Lehtonen",
    "Larisa Shaidurova",
    "Laura Gimmler",
    "Lauri Vuorinen",
    "Lauris Kaparkalejs",
    "Lea Einfalt",
    "Leanid Karneyenka",
    "Lena Einsiedler",
    "Lenka Munclingerova",
    "Lennart Mets",
    "Lidia Durkina",
    "Lidija Durkina",
    "Liliia Vasileva",
    "Lina Andersson",
    "Lisa Eriksson",
    "Lou Reynaud",
    "Luca Orlandi",
    "Lucia Anger",
    "Ludvig Berg",
    "Magnus Stensas",
    "Maja Axelsson",
    "Marcus Hellner",
    "Margot Tirloy",
    "Margrethe Bergane",
    "Maria Magnusson",
    "Marianna Longa",
    "Marit Björgen",
    "Marius Cebulla",
    "Marjaana Pitkänen",
    "Marte Maehlum Johansen",
    "Marthe Kristoffersen",
    "Martin Bajčičák",
    "Martin Collet",
    "Martin Kirkeberg Moerk",
    "Martin Koukal",
    "Martin Otčenáš",
    "Martin Weisheit",
    "Martine Lorgen Ovrebust",
    "Martti Jylha",
    "Matej Koznar",
    "Mathias Bognes",
    "Matia Pellegrin",
    "Matis Bouscarra Gaubert",
    "Maxim Kovalev",
    "Maxim Odnodvortsev",
    "Mélissa Gal",
    "Mikhail Semenov",
    "Minna Mikaelsson",
    "Mira Goeransson",
    "Miska Poikkimaki",
    "Moa Lindgren",
    "Monika Skinder",
    "Monique Siegel",
    "Nadia Kaelin",
    "Nadine Laurent",
    "Nadja Kälin",
    "Natalia Morilova",
    "Natalia Nepryaeva",
    "Natalya Ilyina",
    "Nathalie Schwarz",
    "Nejc Brodar",
    "Niclas Steiger",
    "Nicola Wigger",
    "Niko Anttola",
    "Nikolai Fokin",
    "Nikolai Pankratov",
    "Ole Christian Mork",
    "Ole Joergen Bruvoll",
    "Oleg Milovanov",
    "Olga Kucheruk",
    "Olga Kutscheruk",
    "Ondrej Horyna",
    "Oyvind Anmarkrud",
    "Perttu Hyvärinen",
    "Petr Sedov",
    "Petra Markelova",
    "Petter Stakson",
    "Petteri Koivisto",
    "Polina Nekrasova",
    "Ragnhild Haga",
    "Reijo Nykänen",
    "Riikka Sarasoja",
    "Rolf Figi",
    "Roman Chekalkin",
    "Roman Tarasov",
    "Sebastian Eisenlauer",
    "Selene Rossi",
    "Sergey Skvortsov",
    "Sergey Volkov",
    "Serguei Chtechoutchkine",
    "Serguei Novikov",
    "Sigrid Leseth Foeyen",
    "Silva Kemppi",
    "Simen Thune Rolfsen",
    "Simon Nordlander",
    "Skar Sindre Bjornestad",
    "Sofia Henriksson",
    "Stian Hallen",
    "Stina Nilsson",
    "Svetlana Kokovina",
    "Svetlana Ovchinnikova",
    "Tatiana Chugaeva",
    "Tatiana Tchugaeva",
    "Thea Krokan Murud",
    "Thomas Wick",
    "Tim Tscharnke",
    "Tove Ericsson",
    "Ursina Badilatti",
    "Vaclav Kupilik",
    "Václav Svub",
    "Vadim Sannikov",
    "Valentina Novikova",
    "Vesna Fabjan",
    "Victoria Carl",
    "Vincent Buiatti",
    "Vladim Sannikov",
    "Vladimir Tokarev",
    "Yulia Muhometzianova",
    "Yuliya Chepalova",
    "Zuzana Holikova",
    "Zuzana Kocumova",
    "Adam Cieslar",
    "Alen Turjak",
    "Anja Rathbeg",
    "Annalena Slamik",
    "Anne Haeckel",
    "Annika Sieff",
    "Bejam Lizon Au Cire",
    "Benedikt Gräbert",
    "Benedikt Schwaiger",
    "Brice Ottonello",
    "Bryan Venturini",
    "Cindy Haasch",
    "Constantin Müller",
    "Constantin Schnurr",
    "Daniel Rieder",
    "David Welde",
    "Eidar Johan Stroem",
    "Francois Braud",
    "Giada Delugan",
    "Greta Pinzani",
    "Iacopo Bortolas",
    "Ilkka Herola",
    "Jakob Lange",
    "Jani Peltola",
    "Jason Lamy Chappuis",
    "Jiri Konvalinka",
    "Joakim Klaussen Aakvik",
    "Laura Pletz",
    "Lilian Vaxelaire",
    "Lisa Hirner",
    "Lisa Marie Hirner",
    "Lukas Dolezal",
    "Mads Kristoffer Waaler",
    "Magdalena Burger",
    "Manuel Faisst",
    "Manuel Senoner",
    "Marco Heinis",
    "Mario Seidl",
    "Maximilian Slamik",
    "Mika Ketterer",
    "Mika Vermeulen",
    "Mitja Oranic",
    "Otto Schall",
    "Paul Gerstgraser",
    "Paul Walcher",
    "Pawel Slowiok",
    "Philipp Kuttin",
    "Philipp Orter",
    "Primoz Zupan",
    "Rok Rozman",
    "Rune Liberg Sannes",
    "Samuel Lev",
    "Samuel Mraz",
    "Severi Taipale",
    "Severin Reiter",
    "Stefano Radovan",
    "Theo Rochat",
    "Thomas Andre Kjelboth",
    "Tim Kopp",
    "Tobias Simon",
    "Trine Goepfert",
    "Trine Gopfert",
    "Tristan Sommerfeldt",
    "Willi Hengelhaupt",
    "Yann Laheurte",
    "David Jost",
    "Eric Canovi",
    "Erik Canovi",
    "Eva Matejovicov",
    "Laia Selles Sanchez",
    "Laila Sellés",
    "Lynn Pollinger",
    "Malin Indergaard",
    "Marcello Scarinzi",
    "Martino Utzeri",
    "Mathieu Pharisa",
    "Melissa Bertolina",
    "Miguel Fenoll",
    "Silvano Wolf",
    "Adrian Schuler",
    "Adrian Tittel",
    "Agnes Reisch",
    "Akseli Kokkonen",
    "Akseli Lajunen",
    "Aleksander Zniszczoł",
    "Aleksandr Loginov",
    "Aleksandr Marchukov",
    "Aleksandra Barantceva",
    "Alena Sutiagina",
    "Alessandro Batby",
    "Alex Reiter",
    "Alina Bobrakova",
    "Andre Fussenegger",
    "Andreas Alamommo",
    "Anette Sagen",
    "Anezka Indrackova",
    "Anja Javoršek",
    "Anna Odine Strom",
    "Anna Rupprecht",
    "Anze Lanisek",
    "Artem Yudin",
    "Axel Mayländer",
    "Aysylu Fakhertdinova",
    "Barbora Blazkova",
    "Ben Bayer",
    "Ben Uwe Bayer",
    "Bernard Dobre",
    "Bor Pavlovčič",
    "Carina Wursthorn",
    "Celina Dollberg",
    "Cene Prevc",
    "Christina Feicht",
    "Clemens Leitner",
    "Daniel Tschofenig",
    "Daniela Iraschko",
    "Dawid Jarzabek",
    "Dawid Kubacki",
    "Domen Prevc",
    "Eirin Maria Kvandal",
    "Elisabeth Raudaschl",
    "Emely Torazza",
    "Florian Menz",
    "Florjan Jelovčan",
    "František Holík",
    "Gerald Wambacher",
    "Gjes Morten Roang",
    "Gorazd Završnik",
    "Gregor Deschwanden",
    "Helena Olsson",
    "Henriette Kraus",
    "Ilya Baskakov",
    "Jacqueline Seifriedsberger",
    "Jaka Oblak",
    "Jakob Steinberger",
    "Jan Habdas",
    "Jan Hoerl",
    "Jana Mrákotová",
    "Janne Happonen",
    "Jannik Faißt",
    "Jarkko Maatta",
    "Joanna Eberle",
    "Johannes Pölz",
    "Jon Aaraas",
    "Jonas Schuster",
    "Jonathan Learoyd",
    "Jonathan Siegel",
    "Joni Markannen",
    "Juho Ojala",
    "Julia Mühlbacher",
    "Julian Fussi",
    "Julian Hahn",
    "Julian Wienerroither",
    "Julija Sršen",
    "Karolina Indrackova",
    "Katarina Pirnovar",
    "Katra Komar",
    "Katrin Stefaner",
    "Kiril Kotik",
    "Klemens Joniak",
    "Klemens Murańka",
    "Klemens Staszel",
    "Kristina Zakirova",
    "Krzysztof Biegun",
    "Krzysztof Kojzar",
    "Lasse Deimel",
    "Lean Niederberger",
    "Lena Selbach",
    "Lidiia Iakovleva",
    "Louis Obersteiner",
    "Lovro Vodušek",
    "Ludwig Pohle",
    "Luisa Gorlich",
    "Luka Filip",
    "Lukas Nellenschulte",
    "Maksim Bartolj",
    "Maksim Sergeev",
    "Marcin Wróbel",
    "Mariia Iakovleva",
    "Marine Bressand",
    "Mario Mendel",
    "Marita Kramer",
    "Marius Lindvik",
    "Martina Zanitzer",
    "Mathis Contamine",
    "Mats Sohagen Berggaard",
    "Max Schmalnauer",
    "Maximilian Mechler",
    "Maximilian Steiner",
    "Michael Falkensteiner",
    "Michael Herrmann",
    "Michael Zachrau",
    "Michaela Rajnochova",
    "Miika Taskinen",
    "Miika Ylipulli",
    "Nadine Färber",
    "Natalia Slowik",
    "Natalie Dejmkova",
    "Nejc Seretinek",
    "Nicolas Feltner",
    "Nik Heberle",
    "Nika Kriznar",
    "Nika Prevc",
    "Niko Kytoesaho",
    "Niko Löytäinen",
    "Noelia Vuerich",
    "Nora Midtsundstad",
    "Paul Winter",
    "Peter Prevc",
    "Philipp Raimund",
    "Pola Bełtowska",
    "Raffael Zimmermann",
    "Robert Honeren Johansson",
    "Robert Szymeczek",
    "Rok Benkovic",
    "Roland Muller",
    "Romane Dieu",
    "Sebastian Bradatsch",
    "Selina Alma Freitag",
    "Selina Kolle",
    "Simon Greiderer",
    "Simon Steinbeisser",
    "Simon Steinberger",
    "Sina Arnet",
    "Sofia Tikhonova",
    "Sonja Schoitsch",
    "Sophie Kothbauer",
    "Stefan Kaiser",
    "Stephan Embacher",
    "Taja Bodlaj",
    "Terje Hilde",
    "Thomas Dufter",
    "Thomas Hofer",
    "Timi Zajc",
    "Tine Bogataj",
    "Tinkara Komar",
    "Tomi Jovan",
    "Tymoteusz Amilkiewicz",
    "Ulrich Wohlgenannt",
    "Ulrike Graessler",
    "Urban Rogelj",
    "Veli-Matti Lindstrom",
    "Vincent Descombe-Sevoie",
    "Vladimir Zografski",
    "Wiktor Szozda",
    "Yanick Wasser",
    "Zdena Pešatová",
    "Zvonko Kordez",
    "Achille Leleu",
    "Adéla Keclíková",
    "Agathe Sillieres",
    "Alessandro Lotorto",
    "Anastasia Kurochkina",
    "Andrea Kotsinova",
    "Andreas Hacksteiner",
    "Andreas Kroh",
    "Andrina Maria Salis",
    "Annika Sophie Morgan",
    "Antti Autti",
    "Aydan Karakulak",
    "Benedikt Riel",
    "Bianca Gisler",
    "Carolin Langenhorst",
    "Caroline Weibel",
    "Charlie Lane",
    "Cheyenne Loch",
    "Chloe Trespeuch",
    "Daan Stam",
    "Daniil Donskikh",
    "Dante Brcic",
    "Dimitriy Bazanov",
    "Dmitriy Bazanov",
    "Dmitry Loginov",
    "Dominik Fiegl",
    "Elena Boltaeva",
    "Eleonora Oavliuk",
    "Elin Viken Holvik",
    "Eliot Leicht",
    "Elisa Profanter",
    "Ellie Soutter",
    "Ester Ledecka",
    "Eveliina Taka",
    "Fabian Hartmann",
    "Felicie Leicht",
    "Felix Curt Schwenkel",
    "Francesca Gallina",
    "Francesco Sandrini",
    "Gabriel Adams",
    "Glib Mostovenko",
    "Guillaume Herpin",
    "Heidi Kurkinen",
    "Iikka Bäckström",
    "Ina Meschik",
    "Ivan Ivanov",
    "Jakob Ganserer",
    "Jakub Hrones",
    "Jenny Pleisch",
    "Jerome Lymann",
    "Johann Stefaner",
    "Jules De Sloover",
    "Julia Hennecke",
    "Julian Lueftner",
    "Julie Zogg",
    "Juliette Lefevre",
    "Jure Retuznik",
    "Kamilla Emma Kouzuback",
    "Karolina Sperlova",
    "Katharina Neussner",
    "Kim Martinez",
    "Kristina Holzfeind",
    "Kristina Paul",
    "Krystof Minarik",
    "Ladina Jenny",
    "Lea Casta",
    "Lena Mueller",
    "Leon Beckhaus",
    "Luca Haemmerle",
    "Luca Merimee Mantovani",
    "Luca Tresoldi",
    "Lucas Cornillat",
    "Lukas Mathies",
    "Maeva Martin",
    "Manon Petit",
    "Marcello Grassis",
    "Margarita Garmashova",
    "Marie Gams",
    "Marie Kreisingerova",
    "Marie Marguet",
    "Martin Noerl",
    "Mathias Schoepf",
    "Mathilda Scheid",
    "Matteo Menconi",
    "Maurizio Bormolini",
    "Max Widnig",
    "Merlin Surget",
    "Michael Schreilechner",
    "Michelle Dekker",
    "Mike Santuari",
    "Motiejus Morauskas",
    "Nick Puenter",
    "Nicolas Schutz",
    "Nikita Kovalenko",
    "Niklas Sukke",
    "Nina Micic",
    "Oceane Pozzo",
    "Oskar Kwiatkowski",
    "Pascal Bitschnau",
    "Paulina Ligocka",
    "Petar Gergyovski",
    "Petu Piiroinen",
    "Pia Meusburger",
    "Pia Zerkhold",
    "Radoslav Yankov",
    "Romain Allemand",
    "Romy Van Vreden",
    "Sabine Schoeffmann",
    "Sam Van Lieshout",
    "Sandro Butollo",
    "Sandro Perrenoud",
    "Sarah Dienstbeck",
    "Sebastian Vik",
    "Selin Lakatha",
    "Silvan Flepp",
    "Simona Meiler",
    "Sina Candrian",
    "Soha Janett",
    "Sophia Candrian",
    "Sophie Hediger",
    "Sophie Rodriguez",
    "Stepan Naumov",
    "Stian Aannestad",
    "Stine Espeli Olsen",
    "Tanja Brugger",
    "Telma Sarkipaju",
    "Tervel Zemrifov",
    "Thea Stenshagen",
    "Timon Renfer",
    "Toni-Markus Turunen",
    "Tony Ramoin",
    "Tore-V Holvik",
    "Valery Kolegov",
    "Vanessa Volopichova",
    "Verena Domenig",
    "Vladislav Shkurikhin",
    "Werner Pietsch",
    "Yuna Scheidegger",
    "Yvonne Schuetz",
    "Ziga Ozebek",
    "Zinaida Vasileva"
]

# Function to search and retrieve athlete data from FIS website
def get_fis_athlete_info(name):
    # search_url = f"https://www.fis-ski.com/DB/general/athlete-biography.html?sectorcode=AL&search={name.replace(' ', '%20')}"
    search_url = f"https://www.fis-ski.com/DB/general/search.html?search={name}"
    response = requests.get(search_url)

    if response.status_code != 200:
        print("Pagina web no existe")

    # Parse the XML content
    soup = BeautifulSoup(response.content, 'xml')

    # Extract the desired values
    item = soup.find('item')
    fiscode = None
    birthdate = None
    link = None
    if item:
        name = item.find('name').text
        # sector_code = item.find('sectorcode').text
        fiscode = item.find('fiscode').text
        birth_year = item.find('year').text if item.find('year') else 'Unknown'
        birth_month = item.find('month').text if item.find('month') else 'Unknown'
        birth_day = item.find('day').text if item.find('day') else 'Unknown'
        
        if birth_month == 'Unknown' or birth_day == 'Unknown':
            birthdate = f"{birth_year}"
        else:
            birthdate = f"{birth_year}-{birth_month}-{birth_day}"
        link = item.find('link').text

    return {
        'Name': name,
        'FIS Code': fiscode,
        'Birthdate': birthdate,
        'link': link
    }


# Creating a DataFrame to store athlete information
athlete_data = pd.DataFrame(athlete_names, columns=["Athlete Name"])
athlete_data["FIS Code"] = ""
athlete_data["Birthdate"] = ""

# Loop through each athlete to get their info
for i, name in enumerate(athlete_names):
    print(i) 
    data = get_fis_athlete_info(name)
    athlete_data.at[i, "FIS Code"] = data["FIS Code"]
    athlete_data.at[i, "Birthdate"] = data["Birthdate"]
    time.sleep(1)  # Adding a delay to avoid being blocked by the server

# Saving the data to a CSV file
athlete_data.to_csv("athlete_data.csv", index=False)
print("Data collection complete. Saved to athlete_data.csv")
